// flow-typed signature: 0adcd490fdb95d7c2afde1d6addb5cf8
// flow-typed version: <<STUB>>/@rehooks/component-size_v1.0.2/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rehooks/component-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rehooks/component-size' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@rehooks/component-size/index' {
  declare module.exports: $Exports<'@rehooks/component-size'>;
}
declare module '@rehooks/component-size/index.js' {
  declare module.exports: $Exports<'@rehooks/component-size'>;
}
